  - name: Print IP Address
    shell:  echo Eslam Samy Hosney
    register: print_result

  #show the output on the user/us Cli
  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"
      

  - name: "Install Docker"
    shell: |
        #sudo apt install docker.io
        #sudo apt-get install -y docker.io
        sudo apt-get update && sudo apt-get install docker.io -y
        
  
  - name: "Add user Minikube"
    #become: yes
    shell: |
        #sudo usermod -aG docker $USER && newgrp docker
        sudo groupadd docker
        sudo gpasswd -a $USER docker
        
  - name: "Docker Run"
    shell: |
        docker pull eslamhosney/udacity_devops_engineer_capstone:latest2
        docker run -d -p 8000:80 eslamhosney/udacity_devops_engineer_capstone:latest2
        #kubectl run udacity-devops-engineer-capstone-deploy --image=eslamhosney/udacity_devops_engineer_capstone --port=80 --labels app=udacity-devops-engineer-capstone-deploy
        #kubectl create deployment udacity-devops-engineer-capstone-deploy2 --image=eslamhosney/udacity_devops_engineer_capstone 
    register: print_result

  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"
