Description: >
  Udacity-DevOps-Capstone.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub udacity-devops-backend-${ID}
      GroupDescription: Allow port 22, 80, 8000.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: eslam-keypair # If you use another key pair name, you should change this value to match.
      # If this ami id is not available for you, you can find another (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html)
      # Ubuntu 18 or higher works fine
      ImageId: ami-0629230e074c580f2 #ami-00677bfc4a570cfff #ami-0279c3b3186e54acd #ami-068663a3c619dd892 #ami-04363934db7c747c4 #
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
        - Key: mark
          Value: udacity-devops-backend    
        - Key: scope
          Value: Eslam-Udacity-DevOps-Engineer-Capstone